### ISSUE TITLE
not existing v4l2 device breaks lpmt

### ISSUE THREAD

**Issue by nanu-c** [VideoMapping/lpmtX2#14]
We should fix that with a security check

**Comment by jamet** [comment]
hey @nanu-c , it seems i don't have this problem on my setup as well, even if i don't have v4l2loopback device sets, at setup lpmt the revert to the laptop cam, but i agree with you, there needs to be something cleaner done and a securit check seems a good idea : )

**Comment by jamet** [comment]
@nanu-c , saw your output log from start, here is mine : 

`libv4l2: error setting pixformat: Device or resource busy
[ error ] ofGstUtils: gstHandleMessage(): embedded video playback halted for plugin, module video_source  reported: Device '/dev/video0' is busy
camera with id 2 asked for 640 by 480 - actual size is 640 by 480 
listening for OSC messages on port: 12345
osc control of gui sliders range: min=0 - max=1
setup done! playing now
`

same thing happens, other cams should try to revert to existing cam when setting ID, but /dev/video0 is already busy since it was the first initialised, so there is a cam object, but a blank one, and then lpmt starts fine.

i don't think the crash you experience is due to unexisting webcam but to this : 
`[ error ] ofGstUtils: gstHandleMessage(): embedded video playback halted for plugin, module capsfilter3  reported: Filter caps do not completely specify the output format`

and this 
`Failed to open BO for returned DRI2 buffer (1366x768, dri2 back buffer, named 29).
This is likely a bug in the X Server that will lead to a crash soon.`

i think this is more of an OS-related issue, if you have an other graphic card than intel on your laptop, try to force the OS using this other one, and maybe check if there is no update for your system.

hope it helps a bit...

**Comment by nanu-c** [comment]
i've updated everything and the problem is gone :)
